version: '2.1'

services:
  nginx-proxy:
    build: docker-configs/nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./docker-configs/nginx/certs:/etc/nginx/certs
    ports:
      - "10080:80"
      - "10443:443"
    links:
      - go-19
    depends_on:
      - go-19
    tty: true
  go-19:
    build: docker-configs/golang
    volumes:
      - ./client-apps/fantome-pris-client/dist:/go/src/project/ghost-catch-api/static/html
    command: ./ghost-catch-api
    depends_on:
      - node-89
    tty: true
  node-89:
    build: docker-configs/node
    volumes:
      - ./client-apps:/var/www
    tty: true
