version: '2.1'

services:
  go-19:
    build: docker-configs/golang
    env_file:
      - ./.env
    volumes:
      - ./client-apps/fantome-pris-client/dist:/go/src/project/ghost-catch-api/static/html/games
    command: ./ghost-catch-api
    ports:
      - "${HTTPS}:${HTTPS}"
    depends_on:
      - node-89
    tty: true
  node-89:
    build: docker-configs/node
    volumes:
      - ./client-apps:/var/www
    tty: true
